
GET http://localhost:8001/oauth/token/1
###
POST http://localhost:8001/oauth/token HTTP/1.1
Content-Type: application/json

{
  "grant_type": "password",
  "scope": "scope",
  "username": "adninsijawa.office@gmail.com",
  "password": "password",
  "client_id": 2,
  "client_secret": "client_secret"
}
###
PATCH http://localhost:8001/oauth/token HTTP/1.1
Content-Type: application/json

{
  "token": "1",
  "user_id": 2,
  "client_id": 2,
  "expires": 2
}
###